server:
  port: 8081
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: buyer-service
          uri: 'http://container-buyer:8082'
          predicates:
            - Path=/api/buyer-service/**
            
        - id: stocker-service
          uri: 'http://container-stocker:8083'
          predicates:
            - Path=/api/stocker-service/**
